// Comprehensive Skills Configuration for MARE Assessment
// This file contains all available skills that users can select from

export interface SkillCategory {
  id: string;
  name: string;
  description: string;
  skills: string[];
}

export const SKILL_CATEGORIES: SkillCategory[] = [
  {
    id: 'technical',
    name: 'Technical Skills',
    description: 'Computer and technology-related skills',
    skills: [
      'Programming',
      'Software Development',
      'Web Development',
      'Mobile Development',
      'Database Management',
      'Data Analysis',
      'Machine Learning',
      'Artificial Intelligence',
      'Cybersecurity',
      'Network Security',
      'Cloud Computing',
      'DevOps',
      'System Administration',
      'Testing',
      'Automation Testing',
      'UI/UX Design',
      'Frontend Development',
      'Backend Development',
      'Full Stack Development',
      'API Development',
      'Microservices',
      'Blockchain',
      'Internet of Things',
      'Robotics',
      'Game Development',
      'Computer Graphics',
      'CAD Design',
      '3D Modeling',
      'Electronics',
      'Circuit Design',
      'Embedded Systems',
      'Digital Marketing',
      'SEO',
      'Social Media Marketing',
      'Content Management Systems',
      'E-commerce',
      'IT Support',
      'Technical Writing',
      'Version Control',
      'Agile Methodology',
      'Scrum'
    ]
  },
  {
    id: 'analytical',
    name: 'Analytical Skills',
    description: 'Problem-solving and data analysis abilities',
    skills: [
      'Problem Solving',
      'Critical Thinking',
      'Data Analysis',
      'Statistical Analysis',
      'Research',
      'Market Research',
      'Business Analysis',
      'Financial Analysis',
      'Risk Assessment',
      'Decision Making',
      'Logic',
      'Mathematics',
      'Statistics',
      'Economics',
      'Accounting',
      'Budget Management',
      'Financial Planning',
      'Investment Analysis',
      'Forecasting',
      'Trend Analysis',
      'Process Analysis',
      'Root Cause Analysis',
      'Quality Control',
      'Performance Analysis',
      'Metrics and KPIs',
      'Benchmarking',
      'Strategic Planning',
      'SWOT Analysis',
      'Competitive Analysis',
      'Feasibility Studies'
    ]
  },
  {
    id: 'communication',
    name: 'Communication Skills',
    description: 'Verbal, written, and interpersonal communication',
    skills: [
      'Communication',
      'Public Speaking',
      'Presentation Skills',
      'Writing',
      'Technical Writing',
      'Content Writing',
      'Copywriting',
      'Creative Writing',
      'Journalism',
      'Editing',
      'Proofreading',
      'Translation',
      'Multilingual',
      'English Proficiency',
      'Hindi Proficiency',
      'Regional Languages',
      'Storytelling',
      'Negotiation',
      'Persuasion',
      'Active Listening',
      'Interviewing',
      'Customer Service',
      'Client Relations',
      'Relationship Building',
      'Networking',
      'Conflict Resolution',
      'Mediation',
      'Counseling',
      'Training',
      'Teaching',
      'Mentoring',
      'Facilitation',
      'Cross-cultural Communication',
      'Email Communication',
      'Phone Communication',
      'Video Conferencing'
    ]
  },
  {
    id: 'leadership',
    name: 'Leadership & Management',
    description: 'Leading teams and managing resources',
    skills: [
      'Leadership',
      'Team Management',
      'Project Management',
      'People Management',
      'Strategic Leadership',
      'Change Management',
      'Organizational Development',
      'Performance Management',
      'Talent Management',
      'Succession Planning',
      'Delegation',
      'Motivation',
      'Coaching',
      'Employee Development',
      'Team Building',
      'Collaboration',
      'Cross-functional Leadership',
      'Budget Management',
      'Resource Planning',
      'Time Management',
      'Priority Setting',
      'Goal Setting',
      'Vision Development',
      'Decision Making',
      'Risk Management',
      'Crisis Management',
      'Stakeholder Management',
      'Vendor Management',
      'Contract Management',
      'Operations Management',
      'Supply Chain Management',
      'Quality Management',
      'Process Improvement',
      'Lean Management',
      'Six Sigma'
    ]
  },
  {
    id: 'creative',
    name: 'Creative Skills',
    description: 'Artistic and design capabilities',
    skills: [
      'Creativity',
      'Design',
      'Graphic Design',
      'Web Design',
      'UI/UX Design',
      'Interior Design',
      'Fashion Design',
      'Product Design',
      'Industrial Design',
      'Architecture',
      'Visual Arts',
      'Drawing',
      'Painting',
      'Sculpture',
      'Photography',
      'Video Production',
      'Video Editing',
      'Animation',
      '3D Animation',
      'Motion Graphics',
      'Visual Effects',
      'Sound Design',
      'Music Production',
      'Musical Instruments',
      'Singing',
      'Dancing',
      'Acting',
      'Theatre',
      'Film Making',
      'Scriptwriting',
      'Storyboarding',
      'Brand Design',
      'Logo Design',
      'Typography',
      'Color Theory',
      'Adobe Creative Suite',
      'Photoshop',
      'Illustrator',
      'InDesign',
      'After Effects',
      'Premiere Pro'
    ]
  },
  {
    id: 'interpersonal',
    name: 'Interpersonal Skills',
    description: 'Working with people and social abilities',
    skills: [
      'Teamwork',
      'Collaboration',
      'Empathy',
      'Emotional Intelligence',
      'Social Skills',
      'Interpersonal Skills',
      'Cultural Sensitivity',
      'Diversity and Inclusion',
      'Patience',
      'Adaptability',
      'Flexibility',
      'Resilience',
      'Stress Management',
      'Work-Life Balance',
      'Self-Motivation',
      'Initiative',
      'Proactive Approach',
      'Reliability',
      'Punctuality',
      'Professional Ethics',
      'Integrity',
      'Honesty',
      'Accountability',
      'Responsibility',
      'Customer Focus',
      'Service Orientation',
      'Hospitality',
      'Sales',
      'Relationship Management',
      'Networking',
      'Community Building',
      'Volunteer Work',
      'Social Work',
      'Counseling',
      'Psychology',
      'Behavioral Analysis'
    ]
  },
  {
    id: 'business',
    name: 'Business Skills',
    description: 'Commercial and entrepreneurial abilities',
    skills: [
      'Business Development',
      'Entrepreneurship',
      'Sales',
      'Marketing',
      'Digital Marketing',
      'Brand Management',
      'Product Management',
      'Product Marketing',
      'Market Analysis',
      'Customer Research',
      'Business Strategy',
      'Business Planning',
      'Financial Management',
      'Revenue Generation',
      'Profit Optimization',
      'Cost Management',
      'Pricing Strategy',
      'Competitive Analysis',
      'Partnership Development',
      'Vendor Relations',
      'Contract Negotiation',
      'Deal Closing',
      'CRM Management',
      'Lead Generation',
      'Customer Acquisition',
      'Customer Retention',
      'Account Management',
      'B2B Sales',
      'B2C Sales',
      'E-commerce',
      'Retail Management',
      'Supply Chain',
      'Logistics',
      'Operations',
      'Process Optimization',
      'Lean Startup',
      'MVP Development',
      'Growth Hacking',
      'Fundraising',
      'Investor Relations'
    ]
  },
  {
    id: 'scientific',
    name: 'Scientific & Research',
    description: 'Science, research, and academic skills',
    skills: [
      'Research',
      'Scientific Method',
      'Data Collection',
      'Experimentation',
      'Hypothesis Testing',
      'Literature Review',
      'Academic Writing',
      'Peer Review',
      'Grant Writing',
      'Laboratory Skills',
      'Field Research',
      'Qualitative Research',
      'Quantitative Research',
      'Survey Design',
      'Interview Techniques',
      'Observation Skills',
      'Documentation',
      'Report Writing',
      'Publication',
      'Conference Presentation',
      'Teaching',
      'Curriculum Development',
      'Educational Technology',
      'Biology',
      'Chemistry',
      'Physics',
      'Mathematics',
      'Environmental Science',
      'Medical Knowledge',
      'Healthcare',
      'Pharmaceutical Knowledge',
      'Agricultural Science',
      'Veterinary Science',
      'Psychology',
      'Sociology',
      'Anthropology',
      'Political Science',
      'History',
      'Geography',
      'Linguistics'
    ]
  },
  {
    id: 'technical_trades',
    name: 'Technical Trades',
    description: 'Hands-on technical and mechanical skills',
    skills: [
      'Mechanical Skills',
      'Electrical Work',
      'Plumbing',
      'Carpentry',
      'Welding',
      'Construction',
      'HVAC',
      'Automotive Repair',
      'Machinery Operation',
      'Equipment Maintenance',
      'Tool Usage',
      'Safety Protocols',
      'Blueprint Reading',
      'Technical Drawing',
      'Manufacturing',
      'Assembly',
      'Quality Inspection',
      'Troubleshooting',
      'Repair',
      'Installation',
      'Calibration',
      'Precision Work',
      'Hand-Eye Coordination',
      'Physical Stamina',
      'Heavy Lifting',
      'Working at Heights',
      'Confined Space Work',
      'Hazardous Materials',
      'First Aid',
      'CPR',
      'Emergency Response',
      'Fire Safety',
      'Workplace Safety',
      'OSHA Compliance',
      'Environmental Health',
      'Risk Assessment'
    ]
  },
  {
    id: 'language_cultural',
    name: 'Language & Cultural',
    description: 'Language proficiency and cultural understanding',
    skills: [
      'English',
      'Hindi',
      'Bengali',
      'Telugu',
      'Marathi',
      'Tamil',
      'Gujarati',
      'Urdu',
      'Kannada',
      'Odia',
      'Punjabi',
      'Malayalam',
      'Assamese',
      'Sanskrit',
      'French',
      'German',
      'Spanish',
      'Chinese',
      'Japanese',
      'Korean',
      'Arabic',
      'Russian',
      'Translation',
      'Interpretation',
      'Cross-cultural Communication',
      'Cultural Sensitivity',
      'International Relations',
      'Diplomacy',
      'Cultural Research',
      'Anthropology',
      'Sociology',
      'History',
      'Literature',
      'Philosophy',
      'Religious Studies',
      'Art History',
      'Music Theory',
      'Traditional Arts',
      'Folk Culture',
      'Heritage Preservation',
      'Tourism',
      'Travel Planning'
    ]
  }
];

// Flatten all skills for easy searching
export const ALL_SKILLS: string[] = SKILL_CATEGORIES.reduce((acc, category) => {
  return [...acc, ...category.skills];
}, [] as string[]);

// Skills mapped to career keywords for OR search functionality
export const SKILL_TO_CAREER_KEYWORDS: Record<string, string[]> = {
  'Communication': ['communication', 'speaking', 'presentation', 'writing', 'customer service', 'teaching', 'training', 'sales', 'marketing', 'public relations'],
  'Programming': ['software', 'developer', 'programming', 'coding', 'engineer', 'computer', 'technology', 'IT', 'python', 'java', 'javascript'],
  'Leadership': ['manager', 'director', 'leader', 'supervisor', 'executive', 'head', 'chief', 'coordinator', 'team lead'],
  'Problem Solving': ['analyst', 'consultant', 'researcher', 'scientist', 'engineer', 'troubleshoot', 'analytical', 'critical thinking'],
  'Creativity': ['designer', 'artist', 'creative', 'content', 'marketing', 'advertising', 'media', 'design', 'innovation'],
  'Teaching': ['teacher', 'educator', 'instructor', 'trainer', 'professor', 'tutor', 'academic', 'education'],
  'Healthcare': ['doctor', 'nurse', 'medical', 'health', 'physician', 'therapist', 'pharmacist', 'clinical'],
  'Sales': ['sales', 'business development', 'account manager', 'relationship manager', 'marketing', 'business'],
  'Finance': ['financial', 'accountant', 'banking', 'investment', 'analyst', 'finance', 'economics'],
  'Engineering': ['engineer', 'technical', 'design', 'development', 'construction', 'manufacturing', 'mechanical'],
  'Research': ['researcher', 'scientist', 'analyst', 'academic', 'laboratory', 'study', 'investigation'],
  'Management': ['manager', 'director', 'supervisor', 'coordinator', 'administrator', 'executive', 'operations'],
  'Data Analysis': ['analyst', 'data', 'statistics', 'research', 'scientist', 'business intelligence', 'analytics'],
  'Customer Service': ['customer', 'service', 'support', 'relations', 'representative', 'associate', 'help desk'],
  'Project Management': ['project', 'manager', 'coordinator', 'planner', 'operations', 'administrator', 'scrum']
};

// Industry categories for better filtering
export const INDUSTRY_CATEGORIES = [
  'Technology',
  'Healthcare',
  'Finance',
  'Education',
  'Engineering',
  'Creative',
  'Business',
  'Government',
  'Agriculture',
  'Environment',
  'Manufacturing',
  'Retail',
  'Transportation',
  'Construction',
  'Legal',
  'Media',
  'Sports',
  'Hospitality',
  'Non-profit',
  'Consulting'
];

// Function to get skills by category
export const getSkillsByCategory = (categoryId: string): string[] => {
  const category = SKILL_CATEGORIES.find(cat => cat.id === categoryId);
  return category ? category.skills : [];
};

// Function to search skills
export const searchSkills = (query: string): string[] => {
  const lowercaseQuery = query.toLowerCase();
  return ALL_SKILLS.filter(skill => 
    skill.toLowerCase().includes(lowercaseQuery)
  );
};

// Function to get career keywords for a skill
export const getCareerKeywordsForSkill = (skill: string): string[] => {
  return SKILL_TO_CAREER_KEYWORDS[skill] || [skill.toLowerCase()];
};
